/**
 * Luminous Skin Clinic - Leeds
 * Central Data Store
 */

export const CLINIC_INFO = {
  name: "Luminous Skin Clinic",
  shortName: "Luminous",
  tagline: "Your Skin. Your Confidence. Your Glow.",
  subTagline: "Personalised skin, facial and wellness treatments in Leeds.",
  location: "Leeds, West Yorkshire, United Kingdom",
  address: "Near Elland Road Stadium, Beeston, Leeds, LS11",
  email: "info@luminousskinclinic.co.uk",
  phone: "+44 7950 774790",
  hours: [
    { days: "Monday - Friday", time: "9:30 AM - 6:30 PM" },
    { days: "Saturday", time: "10:00 AM - 5:00 PM" },
    { days: "Sunday", time: "By Appointment Only" },
  ],
  socials: {
    whatsapp: "https://wa.me/447950774790",
    instagram: "https://www.instagram.com/luminouss_skin_clinic",
    tiktok: "https://www.tiktok.com/@luminous_skin_clinic",
    facebook: "https://www.facebook.com/share/1CYA2nkRLr/?mibextid=wwXIfr",
    linktree: "https://linktr.ee/luminousskinclinic",
    trustpilot: "https://uk.trustpilot.com/review/luminousskinclinic.co.uk?utm_content=link_in_bio&utm_medium=trustbox&utm_source=TrustBoxReviewCollector",
  },
  founder: {
    name: "Madiha Naz",
    nickname: "Madi",
    role: "Founder & Owner",
    title: "Certified Beauty Therapist & Lead Facialist in Leeds",
    experience: "Over 5+ Years Experience",
    bio: "I’m Madi, the founder and owner of Luminous Skin business — a sanctuary where beauty, science, and serenity come together. With over five years of experience as a certified Beauty Therapist and one of the best facialists in Leeds, my passion lies in helping clients achieve naturally radiant, healthy skin through safe, advanced, and effective treatments. Known for my calm, kind, and friendly nature, I believe that skincare is more than a treatment — it’s an experience of care, confidence, and well-being. Every session is thoughtfully designed to deliver visible results while providing a moment of pure relaxation. At Luminous Skin Clinic, my goal is to create a welcoming space where every client feels valued, cared for, and leaves glowing — inside and out.",
    aboutStory: "Welcome to Luminous Skin Clinic, where beauty meets serenity. More than just a salon, it’s your personal escape to self-care and skin wellness. With years of experience as a certified beauty therapist and one of the best facialists in Leeds, I blend science and relaxation to deliver visible, radiant results. Every treatment is designed to rejuvenate your skin, restore balance, and enhance your natural glow. Using advanced techniques and premium products, we offer a holistic approach to achieving youthful, luminous skin — without invasive procedures. Clients notice fresher, smoother, more radiant skin after their very first session. Step into calm sophistication and let your confidence shine — because at Luminous Skin Clinic, your skin deserves nothing less than perfection.",
  },
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Treatments", href: "/treatments" },
  { label: "Pricing", href: "/pricing" },
  { label: "Results", href: "/results" },
  { label: "Contact", href: "/contact" },
];

export const TRUST_PILLARS = [
  {
    number: "01",
    title: "Personalised Treatments",
    description: "Customised clinical formulations tailored specifically to your unique skin type.",
  },
  {
    number: "02",
    title: "Leeds Based Clinic",
    description: "Centrally situated calm, private one-to-one clinic environment in Leeds.",
  },
  {
    number: "03",
    title: "Professional Care",
    description: "Evidence-backed dermatology protocols and certified practitioner attention.",
  },
  {
    number: "04",
    title: "Accessible Pricing",
    description: "Transparent pricing starting from £20 with no hidden consultation add-ons.",
  },
];

export const TREATMENTS = [
  {
    "id": "classic-facial",
    "slug": "classic-facial",
    "title": "Classic Facial",
    "category": "All Clinic Facials",
    "price": 25,
    "popular": true,
    "image": "/home-treatment-1.png",
    "tagline": "Gentle essential skin rejuvenation and deep cellular nourishment",
    "shortDescription": "A personalised clinical facial designed to cleanse, exfoliate, and refresh dull complexions with bespoke botanical nourishment.",
    "fullDescription": "Our Classic Facial combines ultrasonic cleansing, gentle enzymatic exfoliation, and a restorative moisture barrier treatment. Tailored for stressed or tired skin, it restores natural balance and healthy radiance.",
    "benefits": [
      "Instant healthy glow & supple skin finish",
      "Gentle exfoliation without redness or irritation",
      "Balances natural skin barrier moisture levels",
      "Includes tailored lymphatic relaxation massage"
    ],
    "idealFor": "Dullness, uneven texture, routine skin maintenance"
  },
  {
    "id": "extraction-deep-cleansing-facial",
    "slug": "extraction-deep-cleansing-facial",
    "title": "Extraction Deep Cleansing Facial",
    "category": "All Clinic Facials",
    "price": 30,
    "popular": false,
    "image": "/home-treatment-2.png",
    "tagline": "Targeted ultrasonic deep pore cleansing and precision extractions",
    "shortDescription": "Clinical deep-pore decongestion that gently clears stubborn blackheads, comedones, and sebum buildup to prevent future breakouts.",
    "fullDescription": "Utilising sterile clinical extraction protocols alongside steam and ultrasonic purification, this facial decongests clogged follicles while calming active redness and tightening open pores.",
    "benefits": [
      "Clears stubborn blackheads and trapped sebum",
      "Decongests enlarged, suffocated pores",
      "Calming antibacterial post-extraction serum",
      "Smooths skin texture and prevents breakouts"
    ],
    "idealFor": "Congested skin, blackheads, excess oil, breakout-prone complexions"
  },
  {
    "id": "signature-spa-facial",
    "slug": "signature-spa-facial",
    "title": "Signature Spa Facial",
    "category": "All Clinic Facials",
    "price": 25,
    "popular": false,
    "image": "/aboutpage-clinicalphilosophy.png",
    "tagline": "A luxurious bespoke relaxation facial combining botanical care",
    "shortDescription": "A holistic clinical facial pairing potent antioxidant botanicals with sculpting pressure-point massage for complete sensorial wellness.",
    "fullDescription": "This restorative facial immerses you in serene botanical aromatics while delivering clinical-grade moisture serums deep into tired skin layers. Relieves facial muscle strain and revives healthy circulation.",
    "benefits": [
      "Deep relaxation and release of hyperactive facial tension",
      "Restores vibrant, dewy skin hydration",
      "Aromatherapy infusion to calm the central nervous system",
      "Sculpts cheekbones and jawline contours"
    ],
    "idealFor": "Stress, fatigue, dull tone, self-care relaxation"
  },
  {
    "id": "ultimate-glow-facial",
    "slug": "ultimate-glow-facial",
    "title": "Ultimate Glow Facial",
    "category": "All Clinic Facials",
    "price": 90,
    "popular": false,
    "image": "/home-treatment-3.png",
    "tagline": "The premier multi-step brightening and radiance protocol",
    "shortDescription": "High-potency clinical illumination combining lactic exfoliation, active vitamin infusions, and collagen boosting for mirror-like radiance.",
    "fullDescription": "Designed for maximum luminous transformation, the Ultimate Glow Facial utilizes layered clinical resurfacing and concentrated peptide infusion to instantly banish fatigue, hyperpigmentation traces, and texture irregularities.",
    "benefits": [
      "Delivers intense, long-lasting glass-skin radiance",
      "Softens fine expression lines and pigment spots",
      "Multi-depth hyaluronic acid hydration plumping",
      "Ideal red-carpet and special event treatment"
    ],
    "idealFor": "Event preparation, severe dullness, lackluster skin"
  },
  {
    "id": "enzyme-peel-facial-cold-therapy",
    "slug": "enzyme-peel-facial-cold-therapy",
    "title": "Enzyme Peel Facial + Cold Therapy",
    "category": "All Clinic Facials",
    "price": 90,
    "popular": false,
    "image": "/home-treatment-4.png",
    "tagline": "Natural fruit enzyme renewal paired with cryo-soothing therapy",
    "shortDescription": "Non-irritating biological enzyme resurfacing complemented by cryo globes to tighten pores, diminish inflammation, and refine texture.",
    "fullDescription": "Papaya and pineapple botanical enzymes digest keratinized dead cells without mechanical abrasion, followed immediately by sub-zero cryo-wand therapy to seal hydration, calm vascular flushing, and tighten the skin barrier.",
    "benefits": [
      "Dissolves dead stratum corneum cells gently",
      "Cryogenic cold therapy constricts dilated pores",
      "Soothes sensitive, reactive, or flushed skin",
      "Leaves complexion cool, velvety, and ultra-smooth"
    ],
    "idealFor": "Sensitive skin, rosacea-prone skin, rough surface texture"
  },
  {
    "id": "all-anti-aging-facial-massages",
    "slug": "all-anti-aging-facial-massages",
    "title": "All Anti-Aging Facial Massages",
    "category": "All Clinic Facials",
    "price": 90,
    "popular": false,
    "image": "/about-The Leeds-Sanctuary.png",
    "tagline": "Sculpting myofascial lymphatic drainage to lift and firm contours",
    "shortDescription": "Intensive manual face-sculpting therapy stimulating deep collagen fibres, draining lymphatic toxins, and lifting slackened facial contours.",
    "fullDescription": "A specialized aesthetic massage combining intra-oral buccal lifting techniques, myofascial release, and firm acupressure to stimulate microcirculation, reduce fluid retention, and restore natural facial youthfulness without injectables.",
    "benefits": [
      "Visibly sculpts and defines cheekbones and jawline",
      "Stimulates natural dermal collagen & elastin synthesis",
      "Eliminates morning puffiness through lymphatic drainage",
      "Softens nasolabial folds and forehead tension"
    ],
    "idealFor": "Loss of firmness, sagging contours, puffiness, natural anti-aging"
  },
  {
    "id": "swedish-relaxing-therapy",
    "slug": "swedish-relaxing-therapy",
    "title": "Swedish Relaxing Therapy",
    "category": "Massage Therapy",
    "price": 25,
    "popular": true,
    "image": "/about-The Leeds-Sanctuary.png",
    "tagline": "Classic gentle gliding Swedish strokes to melt away muscular stress",
    "shortDescription": "Rhythmic, soothing strokes designed to improve oxygen flow in the blood and release chronic tension from neck, shoulders, and back.",
    "fullDescription": "Our Swedish Relaxing Therapy employs long effleurage strokes, kneading, and light rhythmic tapping. Calibrating therapeutic touch to your preference, it lowers cortisol levels and promotes full-body restorative tranquility.",
    "benefits": [
      "Relieves daily desk-posture stiffness and tension",
      "Increases oxygen circulation and lymphatic flow",
      "Promotes deep, restorative sleep cycles",
      "Tailored pressure for complete comfort"
    ],
    "idealFor": "Overall stress, fatigue, tight upper back, relaxation"
  },
  {
    "id": "deep-tissue-therapy",
    "slug": "deep-tissue-therapy",
    "title": "Deep Tissue Therapy",
    "category": "Massage Therapy",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-1.png",
    "tagline": "Firm therapeutic pressure focused on deeper muscle layers",
    "shortDescription": "Targeted clinical neuromuscular pressure designed to break down chronic adhesions, stubborn knots, and muscular tightness.",
    "fullDescription": "Focusing on the inner layers of muscles and connective tissues, our therapists use slow, deliberate strokes and deep finger pressure to release persistent structural tension, sports fatigue, and postural strain.",
    "benefits": [
      "Breaks up painful scar tissue and muscular knots",
      "Restores range of motion and joint flexibility",
      "Alleviates lower back, neck, and shoulder soreness",
      "Accelerates athletic recovery and lactic acid clearance"
    ],
    "idealFor": "Chronic pain, stubborn muscle knots, gym recovery, postural strain"
  },
  {
    "id": "hot-stone-therapy",
    "slug": "hot-stone-therapy",
    "title": "Hot Stone Therapy",
    "category": "Massage Therapy",
    "price": 35,
    "popular": false,
    "image": "/about-The Leeds-Sanctuary.png",
    "tagline": "Therapeutic basalt volcanic stone warmth for ultimate relaxation",
    "shortDescription": "Smooth heated volcanic basalt stones glide along tense muscles to melt deep stress and restore inner bodily equilibrium.",
    "fullDescription": "Therapeutic basalt stones retain comforting heat that penetrates deep into muscular tissue. The soothing heat encourages vascular dilation, relieving chronic desk posture strain and calming the autonomic nervous system.",
    "benefits": [
      "Penetrating volcanic warmth melts stubborn muscle tension",
      "Enhances blood vessel dilation and toxin drainage",
      "Deeply meditative calm for stressed nervous systems",
      "Harmonises full-body vitality and relaxation"
    ],
    "idealFor": "Chronic muscle tension, cold stiffness, stress relief"
  },
  {
    "id": "aroma-therapy-asmr",
    "slug": "aroma-therapy-asmr",
    "title": "Aroma Therapy & ASMR",
    "category": "Massage Therapy",
    "price": 35,
    "popular": false,
    "image": "/aboutpage-clinicalphilosophy.png",
    "tagline": "Sensory relaxation blending calming botanical oils and soothing techniques",
    "shortDescription": "A multi-sensory therapeutic journey combining tailored essential oils with delicate ASMR relaxation touches to quiet an overactive mind.",
    "fullDescription": "Immerse yourself in therapeutic aromatics blended to match your emotional state, paired with gentle scalp, ear, and neck tactile therapies designed to trigger soothing sensory tingles and profound tranquil mindfulness.",
    "benefits": [
      "Quiets racing thoughts and chronic mental fatigue",
      "Custom essential oil blends (Lavender, Bergamot, Neroli)",
      "Releases scalp and cranial fascia tension",
      "Induces deep state of meditative relaxation"
    ],
    "idealFor": "Anxiety, insomnia, high mental stress, sensory unwind"
  },
  {
    "id": "lymphatic-wood-sculpt-massage",
    "slug": "lymphatic-wood-sculpt-massage",
    "title": "Lymphatic (Wood Sculpt Massage)",
    "category": "Massage Therapy",
    "price": 35,
    "popular": false,
    "image": "/Practitioner-Split-img.png",
    "tagline": "Anatomical wooden tools and lymphatic drainage to sculpt and contour",
    "shortDescription": "Targeted wooden contouring tools combined with manual lymphatic drainage to stimulate circulation, reduce water retention, and tone tissue.",
    "fullDescription": "Maderotherapy (wood therapy) uses crafted anatomical wooden implements to break down localized fat deposits, stimulate sluggish lymph nodes, and boost elastin production, leaving the body sculpted and lighter.",
    "benefits": [
      "Stimulates lymphatic circulation and fluid elimination",
      "Smooths skin appearance and breaks down cellulite",
      "Sculpts natural contours of waist, limbs, and hips",
      "Relieves heavy, swollen sensation in legs and joints"
    ],
    "idealFor": "Fluid retention, sluggish metabolism, body contouring, detoxification"
  },
  {
    "id": "indian-head-hand-foot-reflexology",
    "slug": "indian-head-hand-foot-reflexology",
    "title": "Indian Head, Hand & Foot Reflexology",
    "category": "Massage Therapy",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-2.png",
    "tagline": "Holistic acupressure targeting head, hands, and feet for full balance",
    "shortDescription": "Ancient Ayurvedic head massage combined with targeted hand and foot reflex zones to clear energetic blockages and relieve headaches.",
    "fullDescription": "Combining traditional Champi head and neck massage with precise zone therapy across the soles of the feet and palms of the hands. Clears tension headaches, relaxes eye fatigue, and promotes systemic harmony.",
    "benefits": [
      "Rapid relief from tension headaches and migraine pressure",
      "Relaxes tight neck, jaw, and cranial muscles",
      "Balances vital bodily organs via foot reflex pathways",
      "Nourishing oils promote scalp and hair vitality"
    ],
    "idealFor": "Headaches, TMJ tension, eye strain, holistic rebalancing"
  },
  {
    "id": "led-light-therapy-for-pains-add-on",
    "slug": "led-light-therapy-for-pains-add-on",
    "title": "LED Light Therapy for Pains (Add on)",
    "category": "Massage Therapy",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-4.png",
    "tagline": "Near-infrared and red phototherapy for deep muscular comfort",
    "shortDescription": "Medical-grade 830nm near-infrared and 633nm red wavelength therapy applied directly over sore joints and muscles to reduce inflammation.",
    "fullDescription": "Near-infrared photons penetrate several centimeters into tissue to boost cellular ATP production, increase nitric oxide release, and significantly alleviate chronic joint aches, arthritis discomfort, and muscle strain.",
    "benefits": [
      "Clinically proven reduction in joint and muscle pain",
      "Accelerates cellular ATP and tissue repair",
      "Non-invasive, soothing thermal comfort",
      "Perfect booster alongside manual massage therapy"
    ],
    "idealFor": "Joint aches, back pain, stiff neck, post-workout soreness"
  },
  {
    "id": "led-light-treatment",
    "slug": "led-light-treatment",
    "title": "LED Light Treatment",
    "category": "Facial Skin Treatments",
    "price": 15,
    "popular": false,
    "image": "/home-treatment-4.png",
    "tagline": "Targeted medical phototherapy for calm, revitalised skin",
    "shortDescription": "Non-invasive wavelength light therapy calibrated to calm inflammation, accelerate cellular repair, and banish breakout bacteria.",
    "fullDescription": "Medical phototherapy delivers proven red, blue, and near-infrared wavelengths deep into the dermis. Blue light neutralises acne-causing P. acnes bacteria, while red light invigorates fibroblasts for healing, soothing redness and rosacea-prone skin.",
    "benefits": [
      "Calms active inflammation, redness, and irritation",
      "Destroys acne bacteria safely without peeling",
      "Boosts cellular ATP energy and microcirculation",
      "Relaxing, non-invasive experience with zero downtime"
    ],
    "idealFor": "Acne, rosacea, sensitive skin, post-procedure recovery"
  },
  {
    "id": "skin-regenerate-replenish-oxygen-therapy",
    "slug": "skin-regenerate-replenish-oxygen-therapy",
    "title": "Skin Regenerate & Replenish (Oxygen Therapy)",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-1.png",
    "tagline": "Enriched hyperbaric oxygen infusion carrying vital serums deep",
    "shortDescription": "Pressurised clinical oxygen stream delivering medical peptides, antioxidants, and hyaluronic acid for instantaneous plumpness.",
    "fullDescription": "Pure pressurized cosmetic oxygen delivers micronized active serums deep beneath the epidermis. Re-energizes tired, oxygen-depleted skin cells caused by city pollution and fatigue, producing an instantly refreshed, dewy finish.",
    "benefits": [
      "Deeply hydrates and plumps surface expression lines",
      "Antibacterial oxygen barrier defense against pollutants",
      "Revives sluggish, grey, or exhausted complexions",
      "Zero redness, irritation, or downtime"
    ],
    "idealFor": "Dehydration, urban skin, dullness, event preparation"
  },
  {
    "id": "full-hydrafacial-inc-ot-rf-led",
    "slug": "full-hydrafacial-inc-ot-rf-led",
    "title": "Full Hydrafacial Inc.(OT + RF + LED)",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": true,
    "image": "/home-treatment-3.png",
    "tagline": "Comprehensive multi-modality hydro-dermabrasion with RF and LED",
    "shortDescription": "Our flagship facial combining vortex suction pore cleansing, Oxygen Therapy, Radio Frequency collagen stimulation, and LED phototherapy.",
    "fullDescription": "The gold-standard aesthetic treatment combining vortex hydro-cleansing, gentle acid peeling, ultrasonic serum infusion, RF skin firming, oxygen therapy, and soothing LED lights. Total skin transformation in a single session.",
    "benefits": [
      "Vortex suction extracts deep blackheads & oil plugs",
      "Radiofrequency thermal energy tightens skin laxity",
      "Oxygen therapy infuses concentrated vitamins",
      "LED phototherapy locks in clinical radiance"
    ],
    "idealFor": "Total skin renewal, enlarged pores, lines, uneven tone"
  },
  {
    "id": "micro-hydro-dermabrasion-with-ot",
    "slug": "micro-hydro-dermabrasion-with-ot",
    "title": "Micro/Hydro Dermabrasion with OT",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-2.png",
    "tagline": "Diamond-tip resurfacing paired with fluid hydro-extraction",
    "shortDescription": "Dual-action physical exfoliation and gentle fluid peeling that sweeps away dull keratin cells while infusing oxygenated serums.",
    "fullDescription": "Combines precision diamond abrasion to refine rough surface texture with hydro-suction that flushes impurities from pores. Completed with an oxygen therapy mist to promote cellular regeneration and suppleness.",
    "benefits": [
      "Refines rough texture and enlarged pore borders",
      "Fades superficial sun damage and light pigmentation",
      "Painless extraction of persistent blackheads",
      "Leaves skin sensationally smooth and glowing"
    ],
    "idealFor": "Hyperpigmentation, sun damage, stubborn blackheads, rough texture"
  },
  {
    "id": "acne-treatment-high-frequency",
    "slug": "acne-treatment-high-frequency",
    "title": "Acne Treatment (High Frequency)",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": false,
    "image": "/Practitioner-Split-img.png",
    "tagline": "Antibacterial high-frequency electrical ozone therapy",
    "shortDescription": "A specialized argon glass electrode emitting enriched oxygen to purify breakout-prone skin, shrink pores, and stimulate healing.",
    "fullDescription": "High-frequency therapy generates a mild electrical current creating an ozone-rich antibacterial environment on the skin's surface. Rapidly dries up active cystic blemishes, reduces swelling, and prevents recurring breakout cycles.",
    "benefits": [
      "Rapidly reduces inflamed cystic blemishes and spots",
      "Sterilizes acne-causing bacteria deep inside pores",
      "Accelerates post-blemish wound healing and recovery",
      "Regulates sebum production without stripping moisture"
    ],
    "idealFor": "Active acne, cystic breakouts, hormonal flares, congested skin"
  },
  {
    "id": "rf-skin-tightening-full-facial-treatment",
    "slug": "rf-skin-tightening-full-facial-treatment",
    "title": "RF Skin Tightening Full Facial Treatment",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-3.png",
    "tagline": "Radiofrequency thermal energy stimulating deep collagen fibers",
    "shortDescription": "Non-invasive dermal heating that contracts existing collagen and triggers long-term fibroblast renewal for a lifted, firmer profile.",
    "fullDescription": "Bipolar and multipolar RF energy gently heats the deep dermis to 40-42\u00b0C, stimulating immediate collagen contraction and long-term neocollagenesis. Ideal for tightening jowls, softening smile lines, and lifting cheek contours.",
    "benefits": [
      "Visible lifting and tightening of slackened jawlines",
      "Softens nasolabial folds and marionette lines",
      "Promotes ongoing collagen synthesis over 4-6 weeks",
      "Comfortable warm treatment with zero recovery time"
    ],
    "idealFor": "Skin laxity, loss of firmness, early aging, sagging contours"
  },
  {
    "id": "microneedling",
    "slug": "microneedling",
    "title": "Microneedling",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-3.png",
    "tagline": "Natural collagen induction therapy for refined skin texture",
    "shortDescription": "Automated precision microneedling creating sterile micro-channels that trigger powerful collagen and elastin regeneration.",
    "fullDescription": "Medical-grade microneedling triggers your skin's natural healing cascade, boosting fibroblast growth factor and remodeling scarred tissue. Combined with multi-molecular hyaluronic serums to smooth acne pitting and diminish pore size.",
    "benefits": [
      "Noticeable softening of acne scarring and pitted marks",
      "Refines enlarged pores and superficial fine lines",
      "Dramatically improves elasticity and skin bounce",
      "Long-lasting cellular tissue remodeling"
    ],
    "idealFor": "Acne scarring, enlarged pores, premature aging, uneven texture"
  },
  {
    "id": "intense-therapy-for-dry-skin-hydration-infused",
    "slug": "intense-therapy-for-dry-skin-hydration-infused",
    "title": "Intense Therapy for Dry Skin (Hydration Infused)",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-1.png",
    "tagline": "Deep barrier replenishment infused with multi-molecular hyaluronic acid",
    "shortDescription": "Intensive lipid and water restorative protocol formulated to extinguish tightness, flaking, and compromised moisture barriers.",
    "fullDescription": "A specialized barrier-rebuilding treatment delivering essential ceramides, fatty acids, and layered hyaluronic acid directly into parched stratum corneum cells. Seals in deep hydration and protects against environmental moisture loss.",
    "benefits": [
      "Immediate elimination of tightness, flaking, and dry patches",
      "Restores compromised epidermal barrier integrity",
      "Drenches skin in deep, sustained cellular moisture",
      "Leaves complexion calm, supple, and comfortably plump"
    ],
    "idealFor": "Dry skin, chronic flaking, winter dehydration, compromised barrier"
  },
  {
    "id": "dermaplaning-treatment-full-facial",
    "slug": "dermaplaning-treatment-full-facial",
    "title": "Dermaplaning Treatment (Full Facial)",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": true,
    "image": "/home-treatment-2.png",
    "tagline": "Surgical scalpel resurfacing removing peach fuzz and dead buildup",
    "shortDescription": "Precision clinical exfoliation sweeping away dead epidermal layers and vellus hair to reveal radiant, glass-smooth skin.",
    "fullDescription": "Using a sterile medical scalpel, dermaplaning gently clears away weeks of accumulated dead surface cells and fine vellus hair (peach fuzz). Finished with soothing hyaluronic hydration for a silky, light-reflective canvas.",
    "benefits": [
      "Instantly glassy, velvety-smooth skin texture",
      "Eliminates peach fuzz without coarse hair regrowth",
      "Enhances skincare absorption by up to 60%",
      "Flawless, seamless makeup application"
    ],
    "idealFor": "Makeup settling, peach fuzz, dullness, rough surface buildup"
  },
  {
    "id": "ultrasound-galvanic-cold-therapy-add-on",
    "slug": "ultrasound-galvanic-cold-therapy-add-on",
    "title": "Ultrasound, Galvanic & Cold Therapy (Add on)",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": false,
    "image": "/aboutpage-clinicalphilosophy.png",
    "tagline": "Triple-action sonic infusion and cryogenic calming to seal actives",
    "shortDescription": "Sonic wave sonophoresis and galvanic iontophoresis pushing actives deep into the dermis, followed by cryo-tightening therapy.",
    "fullDescription": "Ultrasonic sound waves temporarily increase cell permeability, allowing galvanic microcurrents to drive ionized peptide serums deep into dermal receptors. Cryo cold therapy then seals the active ingredients inside while shrinking pore openings.",
    "benefits": [
      "Dramatically enhances serum penetration and efficacy",
      "Micro-vibrations stimulate lymphatic drainage",
      "Cryo therapy tightens pores and calms post-facial flush",
      "Leaves skin firm, toned, and deeply nourished"
    ],
    "idealFor": "Maximum product infusion, post-treatment redness, open pores"
  },
  {
    "id": "eyebrow-shaping-tinting-face-threading",
    "slug": "eyebrow-shaping-tinting-face-threading",
    "title": "Eyebrow Shaping & Tinting + Face Threading",
    "category": "Facial Skin Treatments",
    "price": 35,
    "popular": false,
    "image": "/home-treatment-1.png",
    "tagline": "Precision brow architecture, custom tinting, and facial threading",
    "shortDescription": "Bespoke facial grooming including precision brow mapping, custom tint pigmentation, and delicate organic cotton threading.",
    "fullDescription": "Elevate your natural facial symmetry with precise brow architectural mapping, custom semi-permanent tinting tailored to your hair and skin undertones, and gentle full-face organic threading to eliminate stray hairs with clean definition.",
    "benefits": [
      "Flawless brow symmetry tailored to your face shape",
      "Long-lasting rich custom brow tinting",
      "Gentle organic threading suitable for sensitive skin",
      "Polished, beautifully defined facial frame"
    ],
    "idealFor": "Brow grooming, stray facial hair, defined eye framing"
  }
];

export const SKIN_CONCERNS = [
  {
    id: "acne-breakouts",
    slug: "acne-breakouts",
    number: "01",
    title: "Acne & Breakouts",
    subtitle: "Congestion, hormonal flares & active blemishes",
    description: "Explore consultation-led options designed for congested, oily, and breakout-prone skin without harsh stripping.",
    recommendedTreatments: ["high-frequency", "led-light-treatment", "rejuvenating-facial"],
    keyAdvice: "Consistency is vital. Harsh scrubbing often exacerbates inflamed barriers; instead, focus on antibacterial wavelength phototherapy and barrier-nourishing hydration.",
  },
  {
    id: "pigmentation",
    slug: "pigmentation",
    number: "02",
    title: "Pigmentation & Sun Damage",
    subtitle: "Uneven tone, sun spots & post-acne marks",
    description: "Build a personalised clinic plan targeting uneven-looking tone, melasma traces, and visible post-inflammatory marks.",
    recommendedTreatments: ["microdermabrasion", "microneedling", "led-light-treatment"],
    keyAdvice: "Safe exfoliation paired with cellular renewal therapies promotes fresh, evenly pigmented skin while daily broad-spectrum SPF defends your results.",
  },
  {
    id: "dull-skin",
    slug: "dull-skin",
    number: "03",
    title: "Dull Skin & Fatigue",
    subtitle: "Tired appearance, environmental stress & lack of glow",
    description: "Refresh tired-looking skin with professional exfoliation, active hydration, and therapeutic glow-boosting care.",
    recommendedTreatments: ["dermaplaning", "rejuvenating-facial", "facial-massage"],
    keyAdvice: "Dead skin accumulation blocks light reflection. A single session of dermaplaning or an enzymatic facial restores instant radiance.",
  },
  {
    id: "dry-skin",
    slug: "dry-skin",
    number: "04",
    title: "Dry & Dehydrated Skin",
    subtitle: "Tightness, flaking, seasonal dehydration & dullness",
    description: "Choose gentle, comfort-focused clinical treatments that support a replenished, plump, and fortified moisture barrier.",
    recommendedTreatments: ["rejuvenating-facial", "led-light-treatment", "facial-massage"],
    keyAdvice: "Dehydrated skin lacks water, while dry skin lacks oil. Our bespoke facials replenish both with hyaluronic acid infusions and peptide lipids.",
  },
  {
    id: "fine-lines",
    slug: "fine-lines",
    number: "05",
    title: "Fine Lines & Elasticity",
    subtitle: "Premature aging, loss of firmness & expression lines",
    description: "Explore skin-renewal treatments selected around your age-well goals, suitability, and natural collagen enhancement.",
    recommendedTreatments: ["microneedling", "led-light-treatment", "microdermabrasion"],
    keyAdvice: "Stimulating your body's intrinsic collagen production with microneedling provides lasting structural refinement that compounds over time.",
  },
  {
    id: "uneven-texture",
    slug: "uneven-texture",
    number: "06",
    title: "Uneven Texture & Pores",
    subtitle: "Rough texture, enlarged pores & superficial scarring",
    description: "Professional treatments engineered for a noticeably smoother, refined, and velvety skin surface finish.",
    recommendedTreatments: ["dermaplaning", "microneedling", "microdermabrasion"],
    keyAdvice: "Combining physical resurfacing with micro-channeling resurfaces the epidermis while refining pore structure from the inside out.",
  },
];

export const REVIEWS = [
  {
    "id": "6a96c2d5f64887c81b85a7ad",
    "consumerId": "5919cd7f0000ff000a9876e0",
    "author": "Nadia",
    "treatment": "Bespoke Facial Treatment",
    "rating": 5,
    "date": "1 Sept 2026",
    "experiencedDate": "1 Sept 2026",
    "title": "Absolutely fantastic",
    "quote": "Absolutely fantastic. Madiya was extremely pleasant and focused on what my skin needed and the results were amazing. I have had treatment at various places but this has to be the best service and treatment that worked wonders for ky skin. Would definitely recommend",
    "highlight": "Absolutely fantastic",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6a96c2d5f64887c81b85a7ad"
  },
  {
    "id": "6a9490a87620f01dc81881b0",
    "consumerId": "624df67c2bfe3d0012f003f2",
    "author": "Shazana Hussain",
    "treatment": "Hydro Facial",
    "rating": 5,
    "date": "31 Aug 2026",
    "experiencedDate": "21 Aug 2026",
    "title": "Loved my experience having a hydro…",
    "quote": "Loved my experience having a hydro facial ,amazing results, lovely atmosphere, definitely coming again x",
    "highlight": "Loved my experience having a hydro…",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6a9490a87620f01dc81881b0"
  },
  {
    "id": "6a91e3767a57b36dbbd93a25",
    "consumerId": "6a91e356f7fcf1cb740d6e01",
    "author": "Ada",
    "treatment": "Deep Cleansing & Facial Massage",
    "rating": 4,
    "date": "29 Aug 2026",
    "experiencedDate": "10 Jun 2026",
    "title": "Good reception",
    "quote": "Good reception, and I will recommend the magic ✨ time to everyone who needs to clean up their face or to have a relaxing time 😌 ( massages)!",
    "highlight": "Good reception",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6a91e3767a57b36dbbd93a25"
  },
  {
    "id": "6a90b7e3d9ce8fb25f715223",
    "consumerId": "606630ed2bba26001a1fcd03",
    "author": "Leanne ",
    "treatment": "Hot Stone Massage & Deep Cleansing",
    "rating": 5,
    "date": "28 Aug 2026",
    "experiencedDate": "13 May 2026",
    "title": "The best at what she does!",
    "quote": "I have had lots of treatments with the lovely Madi. Hot stone massage, deep cleansing facial and luxury back polish. All treatments have been a relaxing and great experience.\n\nMadi shows great attention to detail, puts her all into every treatment and makes you feel comfortable and refreshed. I recommend Madi to everyone I know and I will be back again.",
    "highlight": "The best at what she does!",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6a90b7e3d9ce8fb25f715223"
  },
  {
    "id": "6a77a630ef2acfebad9efdfe",
    "consumerId": "60b8c81d293015001924ce92",
    "author": "Gurj",
    "treatment": "Hot Stone Massage",
    "rating": 5,
    "date": "9 Aug 2026",
    "experiencedDate": "8 Aug 2026",
    "title": "I had such a lovely hot stone massage…",
    "quote": "I had such a lovely hot stone massage with Madi. She is incredibly kind, caring, and welcoming.\n\nThe massage was so relaxing, with the perfect amount of pressure, and the hot stones really helped melt away all my tension. I left feeling refreshed, calm, and completely rejuvenated.\n\nMadi has a genuine passion for what she does, and it really shows in the care and attention she gives her clients. I would highly recommend her to anyone looking for a relaxing, high-quality massage. I’ve been going to her for years and I can’t wait to book my next treatment!",
    "highlight": "I had such a lovely hot stone massage…",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6a77a630ef2acfebad9efdfe"
  },
  {
    "id": "6a76f754e76190f878669fa8",
    "consumerId": "5fd7db337669c700195b96c9",
    "author": "LJ",
    "treatment": "Glow Rejuvenating Facial",
    "rating": 5,
    "date": "8 Aug 2026",
    "experiencedDate": "7 Aug 2026",
    "title": "My skin is glowing ",
    "quote": "I just had my first facial and I can't believe the difference its made - my skin is glowing and feels so clean. The atmosphere is relaxing and the service is excellent, would highly recommend. I've already booked my next treatment!",
    "highlight": "My skin is glowing ",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6a76f754e76190f878669fa8"
  },
  {
    "id": "6a76d8c6d8fff0be96b6c336",
    "consumerId": "640afb5660e6910014281cd2",
    "author": "Sahar",
    "treatment": "Relaxing Facial Therapy",
    "rating": 5,
    "date": "8 Aug 2026",
    "experiencedDate": "30 Jun 2026",
    "title": "I had a wonderful experience",
    "quote": "I had a wonderful experience! The atmosphere is very nice, relaxing, and welcoming, and the service was fantastic. Madeeha is so soft-spoken, friendly, and professional. She always takes the time to give me helpful tips and advice, which I really appreciate. I would definitely recommend her!",
    "highlight": "I had a wonderful experience",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6a76d8c6d8fff0be96b6c336"
  },
  {
    "id": "6a24222bca762fc65388b871",
    "consumerId": "664f6c82d11b2960af2c5a05",
    "author": "customer",
    "treatment": "Facial & Hot Stone Massage",
    "rating": 5,
    "date": "6 Jun 2026",
    "experiencedDate": "2 Jun 2026",
    "title": "Facial and hot stone Massage",
    "quote": "I have had a wonderful facial and hot stone massage experience. Madi was very welcoming, professional, and made me feel completely relaxed from start to finish. The facial left my skin feeling refreshed and glowing, and the hot stone massage was incredibly soothing and therapeutic. Madi s attention to detail and caring approach really stood out. I have been coming for 2 years and  highly recommend her services to anyone looking for a relaxing and high-quality treatment.”",
    "highlight": "Facial and hot stone Massage",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6a24222bca762fc65388b871"
  },
  {
    "id": "69fa6bb6b07900f00bf7a517",
    "consumerId": "6610cda0fa77850012cc78db",
    "author": "Faiqa Sheraz",
    "treatment": "Glass Skin Facial Treatment",
    "rating": 5,
    "date": "6 May 2026",
    "experiencedDate": "1 May 2026",
    "title": "Excellent facial treatment 👌 highly…",
    "quote": "Excellent facial treatment 👌 highly recommend to get glas skin.madeeha is a qualified nd v kind,friendly person who makes u so comfortable nd informs u properly about each step of her procedure.",
    "highlight": "Excellent facial treatment 👌 highly…",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/69fa6bb6b07900f00bf7a517"
  },
  {
    "id": "69d1546dba8c80bce1c63c96",
    "consumerId": "61388c9809f640001206e0b9",
    "author": "Nature's Beauty",
    "treatment": "Luminous Spa & Facial Care",
    "rating": 5,
    "date": "5 Apr 2026",
    "experiencedDate": "20 Feb 2026",
    "title": "The best spa I have been to",
    "quote": "The best spa I have been to. Great customer service, best treatment and affordable. I have been several times and I recommend 100%. Mahdi  is an expert at what she does and her customer service is exceptional.",
    "highlight": "The best spa I have been to",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/69d1546dba8c80bce1c63c96"
  },
  {
    "id": "69d1486cd926cacd58c453b0",
    "consumerId": "5e0c809c984836cb587b9ea2",
    "author": "Emma Ward",
    "treatment": "Hot Stone Massage & Facial",
    "rating": 5,
    "date": "5 Apr 2026",
    "experiencedDate": "31 Mar 2026",
    "title": "The best hot stone massages I have ever had! ",
    "quote": "I have been a regular client of Madi's for the last few years. She is always professional and makes me feel at ease. I love my hot stone massages. I always leave feeling very relaxed. She is very knowledgeable. I have also had a couple of facials and my skin has looked lovely and glowing after. I would highly recommend Madi. I would not use anyone else now 😄",
    "highlight": "The best hot stone massages I have ever had! ",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/69d1486cd926cacd58c453b0"
  },
  {
    "id": "69b5e0a2fe1a410a7385e362",
    "consumerId": "63178c0aa77f69001379e3c9",
    "author": "Nn Kk",
    "treatment": "Steam & Hot Towel Facial Massage",
    "rating": 5,
    "date": "15 Mar 2026",
    "experiencedDate": "14 Mar 2026",
    "title": "Highly recommend ",
    "quote": "Have been coming here for the last 2 years having tried different clinics/ people for facials / massages. Madi is absolutely lovely and warm and  her treatments are amazing  and the best I have ever had.She takes time and focuses on your skin concerns. She dedicates your time just on you alone and results are instant.I gave had the steam and hot towel treatment on face and it makes a huge difference. When she finishes, your skin is so clean and glowy and her massages are amazing and relaxing . Her prices are brilliant . I would highly highly recommend.",
    "highlight": "Highly recommend ",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/69b5e0a2fe1a410a7385e362"
  },
  {
    "id": "6998dee8e7c86c02784c3687",
    "consumerId": "6998dedf3cdc492ae8c8d922",
    "author": "Nichola",
    "treatment": "Signature Facial & Massage",
    "rating": 5,
    "date": "21 Feb 2026",
    "experiencedDate": "19 Feb 2026",
    "title": "Madihya is amazing at what she does",
    "quote": "Madihya is amazing at what she does. Her facials and massages are the best I have had and her manner is out of this world. I would recommend her treatments and her knowledge to anyone who asks!",
    "highlight": "Madihya is amazing at what she does",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6998dee8e7c86c02784c3687"
  },
  {
    "id": "698f737f89ce1d901c2cec32",
    "consumerId": "698f735ab2781e0b9d2871aa",
    "author": "Reah",
    "treatment": "Bespoke Facial & Arm Massage",
    "rating": 5,
    "date": "14 Feb 2026",
    "experiencedDate": "20 Jan 2026",
    "title": "Madi’s facials are pure magic",
    "quote": "Madi’s facials are pure magic! From the moment I enter, I know I’m in the best hands. Madi takes such care and time with every detail, making sure each step of the facial is perfect.The included arm and hand massage feels so relaxing and every visit leaves my skin glowing, flawless, and healthy. I’ve seen a real difference in my skin, and more than that, I always leave feeling pampered and cared for. Madi’s facials aren’t just treatments—they’re little moments of self-care I look forward to every time. I wouldn’t go anywhere else, and I can’t recommend her enough!",
    "highlight": "Madi’s facials are pure magic",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/698f737f89ce1d901c2cec32"
  },
  {
    "id": "6979349e3d7d600e1485bcbf",
    "consumerId": "5cbc7580bcc587b44d6b75ad",
    "author": "Naseem Akhtar",
    "treatment": "Therapeutic Massage & Facial",
    "rating": 5,
    "date": "28 Jan 2026",
    "experiencedDate": "23 Jan 2026",
    "title": "I've been several times to Luminous…",
    "quote": "I've been several times to Luminous Salon.  I would 100% recommend it. Madhiya is absolutely fantastic individual. She treats you with upmost respect & individual needs. \n\nSoon as you walk into her salon you feel relax it's amazing tranquil place. She ensures the room is at the right Temp both warm and cold.\n\nMadhiya is excellent in her field she has very gentle yet firm touch. The massage is incredibly relaxing. Her facial are also fantastic which ever you choose you will not be disappointed. \n\nShe's wonderful down to earth she’s genuine, kind and professional cares for her clients needs. \n\nShe goes extra mile when she's treating you. Thank you Madhiya your the best love you ❤️❤️",
    "highlight": "I've been several times to Luminous…",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/6979349e3d7d600e1485bcbf"
  },
  {
    "id": "69739e639309eda2498fda75",
    "consumerId": "60be1b3856122f001945eedc",
    "author": "Bogdana Nickitiuk",
    "treatment": "Facial & Gentle Massage",
    "rating": 5,
    "date": "23 Jan 2026",
    "experiencedDate": "23 Jan 2026",
    "title": "Happy with my facial",
    "quote": "Happy with my facial. Madi is really lovely,very gentle and smart. The facial goes together with massage and it as all amazing. Thank you!",
    "highlight": "Happy with my facial",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/69739e639309eda2498fda75"
  },
  {
    "id": "697363dba95712104daaad50",
    "consumerId": "68fca439fdf7bf4ef5c1bc8d",
    "author": "customer",
    "treatment": "Personalised Skin Treatment",
    "rating": 5,
    "date": "23 Jan 2026",
    "experiencedDate": "23 Jan 2026",
    "title": "Madiha is a professional lovely lady ",
    "quote": "Madiha is a lovely lady and is always professional. Madi makes you feel welcome, is always warm and polite. A lovely relaxing feeling and the treatments are really good at a very good price. I will always recommend.",
    "highlight": "Madiha is a professional lovely lady ",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/697363dba95712104daaad50"
  },
  {
    "id": "69495d05b66291d7402fd1b8",
    "consumerId": "69495cefd7ccaa4fc07900f3",
    "author": "Aroosa",
    "treatment": "Luminous Facial Experience",
    "rating": 5,
    "date": "22 Dec 2025",
    "experiencedDate": "12 Nov 2025",
    "title": "Had a very good experience",
    "quote": "Had a very good experience! Lovely service and amazing results. Thank you so much, felt like I was taken care of at all times. I recommend their services❤️❤️",
    "highlight": "Had a very good experience",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/69495d05b66291d7402fd1b8"
  },
  {
    "id": "692da283c60358f5438e9c83",
    "consumerId": "4fb10f5c0000640001194a01",
    "author": "Olena Todd",
    "treatment": "Signature Facial & Arm Massage",
    "rating": 5,
    "date": "1 Dec 2025",
    "experiencedDate": "25 Nov 2025",
    "title": "Amazing experience! ",
    "quote": "I had an amazing experience at Luminous Skin. From the moment I walked in and until the end of my treatment - the atmosphere felt calm, welcoming and beautifully maintained. I had a facial booked and the experience exceeded my expectations.\nMadi's facial left my skin glowing, refreshed, noticeably smoother and plump. Madi was very knowledgeable and explained each step while making sure I was completely comfortable.\nShe even massaged my arms which was wonderfully relaxing.\nI walked out feeling lighter, rejuvenated and truly pampered.\nI will definitely be returning to Luminous Skin Clinic for my facial and would like to try a full body massage and other treatments. Highly recommended!",
    "highlight": "Amazing experience! ",
    "source": "Trustpilot",
    "verified": true,
    "trustpilotUrl": "https://uk.trustpilot.com/reviews/692da283c60358f5438e9c83"
  }
];

export const RESULTS_CASE_STUDIES = [
  {
    id: "case-1",
    title: "Congestion & Breakout Reduction",
    treatment: "High Frequency + Blue LED Protocol",
    duration: "4 Weeks (3 Sessions)",
    concern: "Hormonal breakouts & persistent pore congestion",
    outcome: "Significant reduction in active inflammatory lesions and calmed redness across the T-zone.",
  },
  {
    id: "case-2",
    title: "Radiance & Surface Texture Renewal",
    treatment: "Dermaplaning + Rejuvenating Facial",
    duration: "Immediate + 2 Weeks Follow-up",
    concern: "Dull, flaky skin and rough texture preventing makeup adhesion",
    outcome: "Elimination of surface vellus hair, luminous light reflection, and velvet-smooth tactile texture.",
  },
  {
    id: "case-3",
    title: "Acne Scar Softening & Pore Refinement",
    treatment: "Microneedling Collagen Induction",
    duration: "12 Weeks (3 Sessions)",
    concern: "Post-inflammatory hyperpigmentation and shallow icepick acne scarring",
    outcome: "Visible dermal remodeling with shallower scar margins and tighter pore architecture.",
  },
  {
    id: "case-4",
    title: "Barrier Restoration & Redness Soothing",
    treatment: "Custom Calm Facial + Red LED Phototherapy",
    duration: "6 Weeks (2 Sessions)",
    concern: "Impaired moisture barrier with sensitive flaking and reactive flushing",
    outcome: "Restored lipid integrity, reduced vascular flushing, and sustained all-day hydration comfort.",
  },
];

export const FAQS = [
  {
    id: "faq-1",
    question: "How do I know which treatment is right for my skin concern?",
    answer: "You do not need to diagnose yourself or know the clinical treatment name before visiting. During your initial one-to-one consultation at our Leeds clinic, we assess your skin barrier, daily routine, and personal goals to recommend the most suitable, effective treatment protocol.",
  },
  {
    id: "faq-2",
    question: "Is there any downtime after treatments like dermaplaning or microneedling?",
    answer: "Our signature rejuvenating facials and dermaplaning require zero downtime—you can step straight out with an instant luminous glow. For microneedling, slight erythema (rosy flushing) is normal and typically subsides within 12–24 hours as natural collagen synthesis begins.",
  },
  {
    id: "faq-3",
    question: "Are appointments strictly private and one-to-one?",
    answer: "Yes, 100%. Luminous operates exclusively by appointment in a calm, private wellness suite located near Elland Road Stadium in Beeston, Leeds LS11. There are no crowded waiting rooms or overlapping bookings; your time is dedicated entirely to you and your skin.",
  },
  {
    id: "faq-4",
    question: "How should I prepare my skin before my appointment?",
    answer: "We advise pausing active exfoliants (such as AHAs, BHAs, glycolic peels, and retinoids) for 3 to 5 days prior to clinical treatments. Avoid direct UV tanning, and arrive hydrated. We always perform a thorough double-cleanse at the start of every treatment.",
  },
  {
    id: "faq-5",
    question: "How many sessions are recommended for optimal, lasting results?",
    answer: "Treatments like dermaplaning, LED phototherapy, and hydrating facials offer immediate visible radiance after just one session. For concerns like acne scarring, pigmentation, or uneven texture, a tailored course of 3 to 6 sessions produces compounding, long-lasting transformation.",
  },
  {
    id: "faq-6",
    question: "What is your clinic cancellation and rescheduling policy?",
    answer: "We kindly request at least 24 hours advance notice for cancellations or appointment adjustments. This allows us to accommodate clients on our Leeds waiting list. Rescheduling can be easily completed online or by contacting us directly.",
  },
];

